nodeLinker: node-modules
# To prevent some malicious postinstall script from executing
enableScripts: false
# Query remote registries to ensure we install a legit version of a package
enableHardenedMode: true
# 7 days (in minutes) to mitigate to reduce the likelihood of installing compromised packages
npmMinimalAgeGate: 10080
